volumes:
  jackery-data:

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/FastPool/Apps/HomeAssistant:/config
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
    user: "568:568"

  jackery-bridge:
    build: .
    image: jackery-bridge:v1.0.1
    container_name: jackery-bridge
    restart: always
    dns:
      - 192.168.86.22 # Local Pi-hole
      - 1.1.1.1       # Cloudflare
      - 1.0.0.1       # Cloudflare Fallback
    environment:
      - JACKERY_USERNAME
      - JACKERY_PASSWORD
      - JACKERY_DEVICE_ID
      - MQTT_BROKER
      - MQTT_PORT
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_DISCOVERY_PREFIX
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
      - POLL_INTERVAL_SEC
      - LOW_BATTERY_THRESHOLD
      - CRITICAL_BATTERY_THRESHOLD
    volumes:
      # Persists token cache to prevent session dropouts during container updates
      - jackery-data:/app/data
    depends_on:
      - mqtt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
